# -*- coding: utf-8 -*-
"""fake_account_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KTac7VwbVHgfcHt0GGG0EUsGDHsXidRI
"""

from google.colab import drive
drive.mount('/content/drive')

!pip -q install -r requirements.txt

import os
project_path = "/content/drive/MyDrive/twitter_fake_detection"
os.chdir(project_path)

!python main.py